name: Build and Deploy File Processing Services

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB: docker.io
  PROJECT_NAME: fileprocessing
  REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_HUB }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate tags
      id: meta
      run: |
        GIT_COMMIT_SHORT=$(git rev-parse --short HEAD)
        TAG="${GITHUB_RUN_NUMBER}-${GIT_COMMIT_SHORT}"
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
        echo "git_commit_short=${GIT_COMMIT_SHORT}" >> $GITHUB_OUTPUT

    - name: Build Docker Images
      run: |
        docker build --network=host -t ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}-api:${{ steps.meta.outputs.tag }} ./api_service
        docker build --network=host -t ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}-processor:${{ steps.meta.outputs.tag }} ./processor_service
        docker build --network=host -t ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}-notifier:${{ steps.meta.outputs.tag }} ./notification_service

    - name: Push Docker Images
      run: |
        docker push ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}-api:${{ steps.meta.outputs.tag }}
        docker push ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}-processor:${{ steps.meta.outputs.tag }}
        docker push ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}-notifier:${{ steps.meta.outputs.tag }}

    - name: Checkout Infrastructure Repo
      uses: actions/checkout@v4
      with:
        repository: chaladak/fileprocessing-infra
        token: ${{ secrets.INFRA_REPO_TOKEN }}
        path: fileprocessing-infra
        ssh-key: ${{ secrets.INFRA_REPO_SSH_KEY }}

    - name: Install tools
      run: |
        # Install yq
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
        
        # Install kustomize
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    - name: Update Image Tags in Infrastructure Repo
      run: |
        cd fileprocessing-infra/deploy/overlays/dev
        
        # Configure git
        git config user.name "${{ secrets.GIT_NAME }}"
        git config user.email "${{ secrets.GIT_EMAIL }}"
        
        # Update kustomization with new image tags
        kustomize edit set image ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}-api:${{ steps.meta.outputs.tag }}
        kustomize edit set image ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}-processor:${{ steps.meta.outputs.tag }}
        kustomize edit set image ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}-notifier:${{ steps.meta.outputs.tag }}
        
        # Commit and push changes
        git add kustomization.yaml
        git commit -m "Update image tags to ${{ steps.meta.outputs.tag }} [skip ci]" || exit 0
        git push
